// Model Data - Fidox Intelligence
// This file contains all model information for dynamic page generation

const MODELS_DATA = [
  {
    id: "claude-opus-5",
    slug: "claude-opus-5",
    name: "Claude Opus 5",
    developer: "Anthropic",
    params: "2T",
    contextWindow: "1M",
    releaseYear: 2026,
    globalScore: 92,
    mmlu: 91,
    gpqa: 88,
    humaneval: 89,
    description: "Le modèle le plus puissant d'Anthropic, conçu pour les tâches complexes de raisonnement et de coding agentic.",
    capabilities: ["Langage avancé", "Coding agentic", "Vision", "Raisonnement multi-étapes"],
    strengths: ["Excellence en coding", "Long contexte 1M tokens", "Raisonnement complexe"],
    weaknesses: ["Coût élevé", "Vitesse inférieure"],
    bestFor: ["Projets coding complexes", "Recherche", "Analyse documentaire"],
    price: "$5/$25 per 1M tokens",
    apiAvailable: true,
    openSource: false,
    category: "Frontier"
  },
  {
    id: "claude-fable-5",
    slug: "claude-fable-5",
    name: "Claude Fable 5",
    developer: "Anthropic",
    params: "2T (fallback Opus 4.8)",
    contextWindow: "1M",
    releaseYear: 2026,
    globalScore: 91,
    mmlu: 90,
    gpqa: 87,
    humaneval: 88,
    description: "Version sécurisée de Mythos 5, avec fallback automatique vers Opus 4.8 pour les requêtes sensibles.",
    capabilities: ["Coding autonome", "Tests automatiques", "Vision", "Mémoire"],
    strengths: ["Sessions autonomes longues", "Sécurité renforcée", "Code qualité production"],
    weaknesses: ["Fallback peut affecter performance", "Disponible uniquement Pro/Max"],
    bestFor: ["Migrations complexes", "Implémentations autonomes", "Projets multi-jours"],
    price: "Inclus Pro/Max/Team",
    apiAvailable: true,
    openSource: false,
    category: "Frontier"
  },
  {
    id: "gpt-5-6-sol",
    slug: "gpt-5-6-sol",
    name: "GPT-5.6 Sol",
    developer: "OpenAI",
    params: "~1.8T",
    contextWindow: "1.05M",
    releaseYear: 2026,
    globalScore: 90,
    mmlu: 89,
    gpqa: 86,
    humaneval: 91,
    description: "Le modèle phare d'OpenAI, optimisé pour le coding et le raisonnement complexe.",
    capabilities: ["Coding multimodal", "Agent workflows", "Computer use", "Raisonnement scientifique"],
    strengths: ["Meilleur en coding", "Efficacité tokens", "Coût réduit"],
    weaknesses: ["Moins fort en GPQA", "Ferme"],
    bestFor: ["Coding professionnel", "Workflows agents", "Recherche technique"],
    price: "$3/$15 per 1M tokens",
    apiAvailable: true,
    openSource: false,
    category: "Frontier"
  },
  {
    id: "grok-4-6",
    slug: "grok-4-6",
    name: "Grok 4.6",
    developer: "xAI",
    params: "Non disclose",
    contextWindow: "500K",
    releaseYear: 2026,
    globalScore: 88,
    mmlu: 87,
    gpqa: 85,
    humaneval: 86,
    description: "Dernier modèle dxAI, performant sur le raisonnement et le coding agent.",
    capabilities: ["Raisonnement multi-étapes", "Coding", "Knowledge work", "Long contexte"],
    strengths: ["Performance frontier", "Intégration X", "Prix compétitif"],
    weaknesses: ["Contexte plus court", "Écosystème plus petit"],
    bestFor: ["Applications X/Twitter", "Coding agentic", "Recherche"],
    price: "$2.50/$12.50 per 1M tokens",
    apiAvailable: true,
    openSource: false,
    category: "Frontier"
  },
  {
    id: "kimi-k3",
    slug: "kimi-k3",
    name: "Kimi K3",
    developer: "Moonshot AI",
    params: "2.8T (104B activated)",
    contextWindow: "1M",
    releaseYear: 2026,
    globalScore: 94,
    mmlu: 93,
    gpqa: 93.5,
    humaneval: 90,
    description: "Le plus grand modèle open-weights jamais publié, par Moonshot AI.",
    capabilities: ["Raisonnement long", "Science", "Coding", "Vision"],
    strengths: ["GPQA record", "Open weights", "1M tokens", "Grande taille"],
    weaknesses: ["Coût self-hosting élevé", "Infrastructure lourde"],
    bestFor: ["Recherche scientifique", "Tâches complexes", "Auto-hébergement"],
    price: "$3/$15 per 1M tokens",
    apiAvailable: true,
    openSource: true,
    category: "Frontier"
  },
  {
    id: "qwen3-8-max",
    slug: "qwen3-8-max",
    name: "Qwen3.8 Max",
    developer: "Alibaba",
    params: "2.4T",
    contextWindow: "1M",
    releaseYear: 2026,
    globalScore: 87,
    mmlu: 86,
    gpqa: 84,
    humaneval: 85,
    description: "Le plus puissant modèle de la série Qwen d'Alibaba, multimodal et open weights.",
    capabilities: ["Multimodal", "Coding", "Recherche", "Long contexte"],
    strengths: ["Open weights", "Bon rapport qualité/prix", "Vision forte"],
    weaknesses: ["Écosystème moins mature"],
    bestFor: ["Applications Chine", "Recherche", "Développement local"],
    price: "$2 per 1M tokens",
    apiAvailable: true,
    openSource: true,
    category: "High-End"
  },
  {
    id: "muse-spark-1-2",
    slug: "muse-spark-1-2",
    name: "Muse Spark 1.2",
    developer: "Muse AI",
    params: "720B",
    contextWindow: "200K",
    releaseYear: 2026,
    globalScore: 82,
    mmlu: 80,
    gpqa: 79,
    humaneval: 83,
    description: "Modèle équilibré avec excellente performance en coding et raisonnement.",
    capabilities: ["Coding", "Raisonnement", "Création contenu"],
    strengths: ["Rapport qualité/prix", "Vitesse", "Fiabilité"],
    weaknesses: ["Contexte moyen", "Moins connu"],
    bestFor: ["Applications web", "Services", "Automatisation"],
    price: "$1.50/$7.50 per 1M tokens",
    apiAvailable: true,
    openSource: false,
    category: "High-End"
  },
  {
    id: "gpt-5-6-terra",
    slug: "gpt-5-6-terra",
    name: "GPT-5.6 Terra",
    developer: "OpenAI",
    params: "~900B",
    contextWindow: "1M",
    releaseYear: 2026,
    globalScore: 86,
    mmlu: 85,
    gpqa: 83,
    humaneval: 84,
    description: "Version équilibrée de GPT-5.6, optimale pour usage général.",
    capabilities: ["Langage", "Coding", "Vision", "Agents"],
    strengths: ["Équilibre perf/coût", "Écosystème OpenAI", "Fiabilité"],
    weaknesses: ["Moins fort que Sol"],
    bestFor: ["Usage général", "Productivité", "Analyse"],
    price: "$1.50/$7.50 per 1M tokens",
    apiAvailable: true,
    openSource: false,
    category: "High-End"
  },
  {
    id: "deepseek-v4-pro",
    slug: "deepseek-v4-pro-0813",
    name: "DeepSeek V4 Pro",
    developer: "DeepSeek",
    params: "Non disclose",
    contextWindow: "1M",
    releaseYear: 2026,
    globalScore: 80,
    mmlu: 78,
    gpqa: 76,
    humaneval: 82,
    description: "Modèle MoE performant avec excellent rapport qualité/prix.",
    capabilities: ["Coding", "Knowledge", "Raisonnement"],
    strengths: ["Prix très bas", "Grand contexte", "Open weights"],
    weaknesses: ["Performance moyenne", "Support limité"],
    bestFor: ["Applications à volume", "Budget limité", "Testing"],
    price: "$0.435/$0.87 per 1M tokens",
    apiAvailable: true,
    openSource: true,
    category: "Value"
  },
  {
    id: "glm-5-2",
    slug: "glm-5-2",
    name: "GLM-5.2",
    developer: "Zhipu AI",
    params: "Non disclose",
    contextWindow: "1M",
    releaseYear: 2026,
    globalScore: 89,
    mmlu: 88,
    gpqa: 85,
    humaneval: 92,
    description: "Meilleur modèle open-weight en coding et agentic benchmarks.",
    capabilities: ["Coding expert", "Agents", "Long contexte", "Vision"],
    strengths: ["Top en coding", "Open source MIT", "Long horizon"],
    weaknesses: ["Écosystème chinois"],
    bestFor: ["Développement logiciel", "Projets autonomes", "Recherche"],
    price: "Gratuit / $1 per 1M tokens",
    apiAvailable: true,
    openSource: true,
    category: "Frontier"
  },
  {
    id: "gpt-5-6-luna",
    slug: "gpt-5-6-luna",
    name: "GPT-5.6 Luna",
    developer: "OpenAI",
    params: "~450B",
    contextWindow: "200K",
    releaseYear: 2026,
    globalScore: 84,
    mmlu: 83,
    gpqa: 81,
    humaneval: 82,
    description: "Version rapide et économique de GPT-5.6.",
    capabilities: ["Langage rapide", "Coding simple", "Assistant"],
    strengths: ["Vitesse", "Prix bas", "Accessibilité"],
    weaknesses: ["Moins performant", "Contexte limité"],
    bestFor: ["Usage quotidien", "Chat", "Tâches simples"],
    price: "$0.75/$3.75 per 1M tokens",
    apiAvailable: true,
    openSource: false,
    category: "Efficiency"
  },
  {
    id: "gemini-3-6-flash",
    slug: "gemini-3-6-flash",
    name: "Gemini 3.6 Flash",
    developer: "Google",
    params: "Non disclose",
    contextWindow: "1M",
    releaseYear: 2026,
    globalScore: 85,
    mmlu: 84,
    gpqa: 82,
    humaneval: 83,
    description: "Optimisé pour les workflows agents et le coding full-stack.",
    capabilities: ["Orchestration multi-étapes", "Refactoring", "Raisonnement"],
    strengths: ["Rapide", "Intégration Google", "Bon coding"],
    weaknesses: ["Pas le meilleur benchmark"],
    bestFor: ["Agents", "Refactoring code", "Apps Google Cloud"],
    price: "$1.50/$7.50 per 1M tokens",
    apiAvailable: true,
    openSource: false,
    category: "High-End"
  },
  {
    id: "motif-3",
    slug: "motif-3",
    name: "Motif 3",
    developer: "Motif AI",
    params: "Non disclose",
    contextWindow: "200K",
    releaseYear: 2026,
    globalScore: 81,
    mmlu: 79,
    gpqa: 78,
    humaneval: 80,
    description: "Nouveau venu prometteur avec bon équilibre performance/coût.",
    capabilities: ["Langage", "Coding", "Analyse"],
    strengths: ["Prix compétitif", "Interface simple"],
    weaknesses: ["Moins testé", "Communauté réduite"],
    bestFor: ["Startups", "PMV rapide", "Prototypage"],
    price: "$1 per 1M tokens",
    apiAvailable: true,
    openSource: false,
    category: "Value"
  },
  {
    id: "minimax-m3",
    slug: "minimax-m3",
    name: "MiniMax-M3",
    developer: "MiniMax",
    params: "Non disclose",
    contextWindow: "1M",
    releaseYear: 2026,
    globalScore: 83,
    mmlu: 82,
    gpqa: 80,
    humaneval: 81,
    description: "Modèle chinois avec large contexte et bonnes capacités.",
    capabilities: ["Langage", "Vision", "Long contexte"],
    strengths: ["1M tokens", "Bon prix", "Spécialisé Asia"],
    weaknesses: ["Moins disponible globalement"],
    bestFor: ["Applications Asie", "Long documents", "Multilingue"],
    price: "$0.80/$4 per 1M tokens",
    apiAvailable: true,
    openSource: false,
    category: "High-End"
  },
  {
    id: "inkling",
    slug: "inkling",
    name: "Inkling",
    developer: "Inkling AI",
    params: "Non disclose",
    contextWindow: "128K",
    releaseYear: 2026,
    globalScore: 78,
    mmlu: 76,
    gpqa: 75,
    humaneval: 77,
    description: "Modèle émergent axé sur la créativité et le raisonnement.",
    capabilities: ["Création contenu", "Raisonnement", "Analyse"],
    strengths: ["Créativité", "Prix bas"],
    weaknesses: ["Nouveau", "Benchmark limités"],
    bestFor: ["Création", "Brainstorming", "Content"],
    price: "$0.50/$2.50 per 1M tokens",
    apiAvailable: true,
    openSource: false,
    category: "Emerging"
  },
  {
    id: "nemotron-3-ultra",
    slug: "nemotron-3-ultra",
    name: "Nemotron 3 Ultra",
    developer: "NVIDIA",
    params: "55B (actif) / 550B (total)",
    contextWindow: "128K",
    releaseYear: 2026,
    globalScore: 86,
    mmlu: 85,
    gpqa: 83,
    humaneval: 84,
    description: "Modèle open frontier de NVIDIA, optimisé pour le raisonnement.",
    capabilities: ["Raisonnement", "Coding", "Orchestration", "Open weights"],
    strengths: ["Open weights", "Gratuit", "Optimisé NVIDIA"],
    weaknesses: ["Taille modeste", "Moins connu"],
    bestFor: ["Self-hosting", "GPU NVIDIA", "Research"],
    price: "Gratuit (self-host)",
    apiAvailable: true,
    openSource: true,
    category: "Open"
  },
  {
    id: "gemini-3-5-flash-lite",
    slug: "gemini-3-5-flash-lite",
    name: "Gemini 3.5 Flash-Lite",
    developer: "Google",
    params: "Non disclose",
    contextWindow: "1M",
    releaseYear: 2026,
    globalScore: 82,
    mmlu: 81,
    gpqa: 79,
    humaneval: 80,
    description: "Version allégée de Gemini pour vitesse et efficacité.",
    capabilities: ["Rapidité", "Coding", "Agents légers"],
    strengths: ["Très rapide", "Bon marché", "1M tokens"],
    weaknesses: ["Performance réduite"],
    bestFor: ["High volume", "Latence faible", "Batch processing"],
    price: "$0.75/$3.75 per 1M tokens",
    apiAvailable: true,
    openSource: false,
    category: "Efficiency"
  },
  {
    id: "solar-open2-250b",
    slug: "solar-open2-250b",
    name: "Solar Open2 250B",
    developer: "Upstage",
    params: "250B",
    contextWindow: "32K",
    releaseYear: 2026,
    globalScore: 79,
    mmlu: 77,
    gpqa: 76,
    humaneval: 78,
    description: "Modèle open source coréen performant avec architecture MoE.",
    capabilities: ["Langage", "Vision", "Coding"],
    strengths: ["Open source", "Bon vision", "Rapport qualité/prix"],
    weaknesses: ["Contexte court", "Moins connu"],
    bestFor: ["Usage général", "Vision", "Startups"],
    price: "$1 per 1M tokens",
    apiAvailable: true,
    openSource: true,
    category: "Value"
  },
  {
    id: "muse-glimmer",
    slug: "muse-glimmer-high",
    name: "Muse Glimmer",
    developer: "Muse AI",
    params: "360B",
    contextWindow: "200K",
    releaseYear: 2026,
    globalScore: 80,
    mmlu: 78,
    gpqa: 77,
    humaneval: 79,
    description: "Version high-performance de Muse pour coding rapide.",
    capabilities: ["Coding rapide", "Raisonnement", "Agents"],
    strengths: ["Vitesse", "Bon coding", "Prix moyen"],
    weaknesses: ["Moins testé en production"],
    bestFor: ["Prototypage rapide", "Coding itératif"],
    price: "$2 per 1M tokens",
    apiAvailable: true,
    openSource: false,
    category: "High-End"
  },
  {
    id: "ax-k2",
    slug: "ax-k2",
    name: "A.X-K2",
    developer: "A.X Labs",
    params: "Non disclose",
    contextWindow: "128K",
    releaseYear: 2026,
    globalScore: 77,
    mmlu: 75,
    gpqa: 74,
    humaneval: 76,
    description: "Nouveau modèle avec approche innovante du raisonnement.",
    capabilities: ["Raisonnement", "Analyse", "Langage"],
    strengths: ["Approche unique", "Prix attractif"],
    weaknesses: ["Très nouveau", "Peu de benchmarks"],
    bestFor: ["Expérimentation", "Cas d'usage niche"],
    price: "$0.75/$3.75 per 1M tokens",
    apiAvailable: true,
    openSource: false,
    category: "Emerging"
  },
  {
    id: "k-exaone-2-0",
    slug: "k-exaone-2-0-0803",
    name: "K-EXAONE 2.0",
    developer: "LG AI",
    params: "Non disclose",
    contextWindow: "32K",
    releaseYear: 2026,
    globalScore: 76,
    mmlu: 74,
    gpqa: 73,
    humaneval: 75,
    description: "Modèle coréen de LG AI, bon pour les tâches asiaticques.",
    capabilities: ["Langage coréen", "Multilingue", "Coding"],
    strengths: ["Coréen excellent", "Open weights", "Bon prix"],
    weaknesses: ["Contexte court", "Support ASIE"],
    bestFor: ["Applications Corée", "Traduction", "Local ASIE"],
    price: "$0.50/$2.50 per 1M tokens",
    apiAvailable: true,
    openSource: true,
    category: "Regional"
  },
  {
    id: "mistral-medium-3-5",
    slug: "mistral-medium-3-5",
    name: "Mistral Medium 3.5",
    developer: "Mistral AI",
    params: "Non disclose",
    contextWindow: "128K",
    releaseYear: 2026,
    globalScore: 84,
    mmlu: 83,
    gpqa: 81,
    humaneval: 82,
    description: "Modèle européen performant avec excellent support multilingue.",
    capabilities: ["Multilingue", "Coding", "Raisonnement", "Agents"],
    strengths: ["Multilingue EU", "Open weights option", "Bonne docs"],
    weaknesses: ["Moins fort que leaders US"],
    bestFor: ["Europe", "Multilingue", "Coding"],
    price: "$1.50/$7.50 per 1M tokens",
    apiAvailable: true,
    openSource: true,
    category: "High-End"
  },
  {
    id: "claude-4-5-haiku",
    slug: "claude-4-5-haiku",
    name: "Claude 4.5 Haiku",
    developer: "Anthropic",
    params: "Non disclose",
    contextWindow: "200K",
    releaseYear: 2026,
    globalScore: 78,
    mmlu: 76,
    gpqa: 75,
    humaneval: 77,
    description: "Version rapide et économique de Claude pour usage courant.",
    capabilities: ["Langage rapide", "Coding basique", "Assistant"],
    strengths: ["Rapide", "Bon marché", "Fiable"],
    weaknesses: ["Moins performant", "Pas pour tâches complexes"],
    bestFor: ["Usage quotidien", "Chat", "Tâches simples"],
    price: "$0.25/$1.25 per 1M tokens",
    apiAvailable: true,
    openSource: false,
    category: "Efficiency"
  },
  {
    id: "nemotron-3-super",
    slug: "nemotron-3-super",
    name: "Nemotron 3 Super",
    developer: "NVIDIA",
    params: "Non disclose",
    contextWindow: "128K",
    releaseYear: 2026,
    globalScore: 83,
    mmlu: 82,
    gpqa: 80,
    humaneval: 81,
    description: "Modèle intermédiaire NVIDIA, bon équilibre performance/coût.",
    capabilities: ["Raisonnement", "Coding", "Vision"],
    strengths: ["Open weights", "Bon prix", "Optimisé GPU"],
    weaknesses: ["Moins fort qu'Ultra"],
    bestFor: ["Self-hosting milieu", "Balance perf/prix"],
    price: "Gratuit (self-host)",
    apiAvailable: true,
    openSource: true,
    category: "Open"
  },
  {
    id: "gpt-oss-120b",
    slug: "gpt-oss-120b-high",
    name: "gpt-oss-120b",
    developer: "Open-source community",
    params: "120B",
    contextWindow: "32K",
    releaseYear: 2026,
    globalScore: 75,
    mmlu: 73,
    gpqa: 72,
    humaneval: 74,
    description: "Modèle open-source communautaire basé sur GPT-4 architecture.",
    capabilities: ["Langage", "Coding", "Open source"],
    strengths: ["Open weights", "Community support", "Gratuit"],
    weaknesses: ["Contexte court", "Performance limitée"],
    bestFor: ["Self-hosting", "Éducation", "Testing"],
    price: "Gratuit",
    apiAvailable: false,
    openSource: true,
    category: "Open"
  },
  {
    id: "nemotron-3-5-lightning",
    slug: "nemotron-3-5-lightning",
    name: "Nemotron 3.5 Lightning",
    developer: "NVIDIA",
    params: "Non disclose",
    contextWindow: "64K",
    releaseYear: 2026,
    globalScore: 81,
    mmlu: 80,
    gpqa: 78,
    humaneval: 79,
    description: "Version ultra-rapide de Nemotron pour latency critique.",
    capabilities: ["Rapidité extrême", "Réponse temps réel"],
    strengths: ["Très rapide", "Faible latence", "Open"],
    weaknesses: ["Contexte court", "Performance moindre"],
    bestFor: [" temps réel", "Chatbots", "API haute fréquence"],
    price: "Gratuit (self-host)",
    apiAvailable: true,
    openSource: true,
    category: "Efficiency"
  },
  {
    id: "command-a-plus",
    slug: "command-a-plus",
    name: "Command A+",
    developer: "Conjecture AI",
    params: "Non disclose",
    contextWindow: "128K",
    releaseYear: 2026,
    globalScore: 85,
    mmlu: 84,
    gpqa: 82,
    humaneval: 83,
    description: "Modèle spécialisé agents avec excellent reasoning.",
    capabilities: ["Agent workflows", "Planning", "Execution multi-tâches"],
    strengths: ["Spécialisé agents", "Bon reasoning", "Open weights"],
    weaknesses: ["Nouveau", "Communauté petite"],
    bestFor: ["Agents autonomes", "Workflows complexes", "Automation"],
    price: "$2 per 1M tokens",
    apiAvailable: true,
    openSource: true,
    category: "High-End"
  }
];

// Get model by slug
function getModelBySlug(slug) {
  return MODELS_DATA.find(m => m.slug === slug) || null;
}

// Get all models
function getAllModels() {
  return MODELS_DATA;
}

// Get models by category
function getModelsByCategory(category) {
  return MODELS_DATA.filter(m => m.category === category);
}

// Get top models by score
function getTopModels(limit = 5) {
  return [...MODELS_DATA].sort((a, b) => b.globalScore - a.globalScore).slice(0, limit);
}

// Generate chart data for model
function getModelChartData(model) {
  return {
    labels: ['MMLU', 'GPQA', 'HumanEval', 'Global'],
    datasets: [{
      label: model.name,
      data: [model.mmlu, model.gpqa, model.humaneval, model.globalScore],
      backgroundColor: '#3a83f7',
      borderRadius: 8
    }]
  };
}

// Export for browser
if (typeof module !== 'undefined' && module.exports) {
  module.exports = { MODELS_DATA, getModelBySlug, getAllModels, getModelsByCategory, getTopModels, getModelChartData };
}