// Model Data - Fidox Intelligence
// Updated with real benchmarks from LMSYS Arena, Artificial Analysis, BenchLM (Aug 2026)

const MODELS_DATA = [
  {
    id: "claude-fable-5",
    slug: "claude-fable-5",
    name: "Claude Fable 5",
    developer: "Anthropic",
    params: "2T (MoE)",
    contextWindow: "1M",
    releaseYear: 2026,
    globalScore: 95,
    mmlu: 93,
    gpqa: 91,
    humaneval: 92,
    lmsysElo: 1506,
    description: "Le modèle le plus performant du classement LMSYS Arena (1506 Elo). Version sécurisée de Mythos 5, conçue pour le coding autonomne longue durée et les tâches agents complexes.",
    capabilities: ["Coding autonome", "Agents multi-étapes", "Vision", "Mémoire longue", "Tests auto"],
    strengths: ["N°1 LMSYS Arena", "Sessions autonomes 24h+", "Qualité code production", "Sécurité renforcée"],
    weaknesses: ["Disponibilité limitée Pro/Max", "Fallback Opus 4.8 pour contenu sensible"],
    bestFor: ["Projets coding complexes", "Migrations autonomes", "Recherche agentique"],
    price: "Inclus Pro/Max/Team",
    apiAvailable: true,
    openSource: false,
    category: "Frontier"
  },
  {
    id: "claude-opus-5-high",
    slug: "claude-opus-5-high",
    name: "Claude Opus 5 (High)",
    developer: "Anthropic",
    params: "2T (MoE)",
    contextWindow: "1M",
    releaseYear: 2026,
    globalScore: 94,
    mmlu: 92,
    gpqa: 90,
    humaneval: 93,
    lmsysElo: 1493,
    description: "Modèle de référence Anthropic pour le raisonnement complexe et le coding agentic. Excellent rapport performance/coût dans la gamme Opus 5.",
    capabilities: ["Raisonnement avancé", "Coding expert", "Agents", "Analyse documentaire"],
    strengths: ["Performances frontier", "Rapport qualité/prix", "Fiabilité élevée"],
    weaknesses: ["Moins fort que Fable 5 en autonomie"],
    bestFor: ["Coding complexe", "Recherche", "Analyse technique"],
    price: "$5/$25 per 1M tokens",
    apiAvailable: true,
    openSource: false,
    category: "Frontier"
  },
  {
    id: "claude-opus-5-max",
    slug: "claude-opus-5-max",
    name: "Claude Opus 5 (Max)",
    developer: "Anthropic",
    params: "2T (MoE)",
    contextWindow: "1M",
    releaseYear: 2026,
    globalScore: 93,
    mmlu: 91,
    gpqa: 89,
    humaneval: 91,
    lmsysElo: 1489,
    description: "Version max de Opus 5, optimisée pour les tâches les plus exigeantes en raisonnement et coding.",
    capabilities: ["Raisonnement extrême", "Coding deep", "Security research", "Science"],
    strengths: ["Top performance", "Code quality", "Raisonnement scientifique"],
    weaknesses: ["Coût plus élevé", "Latence plus longue"],
    bestFor: ["Recherche sécurité", "Problèmes mathématiques", "Scientific computing"],
    price: "$12.50/$62.50 per 1M tokens",
    apiAvailable: true,
    openSource: false,
    category: "Frontier"
  },
  {
    id: "kimi-k3",
    slug: "kimi-k3",
    name: "Kimi K3",
    developer: "Moonshot AI",
    params: "2.8T (104B activated)",
    contextWindow: "1M",
    releaseYear: 2026,
    globalScore: 92,
    mmlu: 90,
    gpqa: 93.5,
    humaneval: 89,
    lmsysElo: 1475,
    description: "Le plus grand modèle open-weights jamais publié (2.8T). Record GPQA Diamond 93.5%, excellent en science et raisonnement.",
    capabilities: ["Science", "Raisonnement long", "Coding", "Vision", "Open weights"],
    strengths: ["Record GPQA", "Open weights 2.8T", "1M tokens", "Leader science"],
    weaknesses: ["Coût self-hosting élevé", "Infrastructure lourde"],
    bestFor: ["Recherche scientifique", "Auto-hébergement", "Tâches complexes"],
    price: "$2.90/$14 per 1M tokens",
    apiAvailable: true,
    openSource: true,
    category: "Frontier"
  },
  {
    id: "gpt-5-6-sol",
    slug: "gpt-5-6-sol",
    name: "GPT-5.6 Sol",
    developer: "OpenAI",
    params: "~1.8T",
    contextWindow: "1.05M",
    releaseYear: 2026,
    globalScore: 91,
    mmlu: 89,
    gpqa: 87,
    humaneval: 91,
    lmsysElo: 1468,
    description: "Leader Terminal-Bench 2.1 (91.9%), excellence en coding terminal et workflows agents. 53.6% ARC-AGI-3.",
    capabilities: ["Coding terminal", "Agents web", "Computer use", "Codex harness"],
    strengths: ["N°1 Terminal-Bench", "Efficacité tokens", "Intégration ChatGPT/Codex"],
    weaknesses: ["Moins fort en GPQA", "Ferme"],
    bestFor: ["Coding production", "Workflows agents", "Automatisation"],
    price: "$3/$15 per 1M tokens",
    apiAvailable: true,
    openSource: false,
    category: "Frontier"
  },
  {
    id: "glm-5-2",
    slug: "glm-5-2",
    name: "GLM-5.2",
    developer: "Zhipu AI",
    params: "753B (MoE)",
    contextWindow: "1M",
    releaseYear: 2026,
    globalScore: 90,
    mmlu: 88,
    gpqa: 86,
    humaneval: 92,
    lmsysElo: 1460,
    description: "Premier modèle open-weight à battre GPT-5 et Claude sur SWE-bench Pro (62.1%). Licence MIT.",
    capabilities: ["Coding expert", "Agents SWE", "Open weights", "Long contexte"],
    strengths: ["SWE-bench Pro 62.1%", "MIT license", "Terminal-Bench 81.0%", "Open source"],
    weaknesses: ["Écosystème chinois"],
    bestFor: ["Développement logiciel", "Projets autonomes", "Self-hosting"],
    price: "Gratuit / $1 per 1M tokens",
    apiAvailable: true,
    openSource: true,
    category: "Frontier"
  },
  {
    id: "grok-4-6",
    slug: "grok-4-6",
    name: "Grok 4.6",
    developer: "xAI",
    params: "Non disclose",
    contextWindow: "500K",
    releaseYear: 2026,
    globalScore: 89,
    mmlu: 87,
    gpqa: 85,
    humaneval: 88,
    lmsysElo: 1445,
    description: "Dernier modèle xAI, performances frontier comparables à Claude et GPT. Intégration native X/Twitter.",
    capabilities: ["Raisonnement multi-étapes", "Coding", "Knowledge work", "Agents"],
    strengths: ["Performance frontier", "Intégration X", "Prix compétitif"],
    weaknesses: ["Contexte 500K vs 1M", "Écosystème plus petit"],
    bestFor: ["Applications X/Twitter", "Coding agentic", "Recherche"],
    price: "$2.50/$12.50 per 1M tokens",
    apiAvailable: true,
    openSource: false,
    category: "Frontier"
  },
  {
    id: "qwen3-8-max",
    slug: "qwen3-8-max",
    name: "Qwen3.8 Max",
    developer: "Alibaba",
    params: "2.4T",
    contextWindow: "1M",
    releaseYear: 2026,
    globalScore: 88,
    mmlu: 86,
    gpqa: 84,
    humaneval: 87,
    lmsysElo: 1440,
    description: "Modèle phare Alibaba, 2.4T paramètres. Leader Vision Arena, excellent rapport qualité/prix.",
    capabilities: ["Multimodal", "Vision", "Coding", "Recherche", "Long contexte"],
    strengths: ["Open weights", "Vision leader", "Bon prix ($2/M)", "1M tokens"],
    weaknesses: ["Écosystème moins mature", "Support ASIE"],
    bestFor: ["Applications Chine", "Vision", "Développement local"],
    price: "$2/$6 per 1M tokens",
    apiAvailable: true,
    openSource: true,
    category: "High-End"
  },
  {
    id: "muse-spark-1-2",
    slug: "muse-spark-1-2",
    name: "Muse Spark 1.2",
    developer: "Muse AI",
    params: "720B",
    contextWindow: "200K",
    releaseYear: 2026,
    globalScore: 86,
    mmlu: 84,
    gpqa: 82,
    humaneval: 85,
    lmsysElo: 1425,
    description: "Modèle équilibré Meta, bon rapport performance/coût. Populaire en Europe.",
    capabilities: ["Coding", "Raisonnement", "Vision", "Agents légers"],
    strengths: ["Bon rapport qualité/prix", "Vitesse", "Fiabilité"],
    weaknesses: ["Contexte 200K", "Moins connu"],
    bestFor: ["Applications web", "Services", "Automatisation"],
    price: "$1.25/$4.25 per 1M tokens",
    apiAvailable: true,
    openSource: false,
    category: "High-End"
  },
  {
    id: "gpt-5-6-terra",
    slug: "gpt-5-6-terra",
    name: "GPT-5.6 Terra",
    developer: "OpenAI",
    params: "~900B",
    contextWindow: "1M",
    releaseYear: 2026,
    globalScore: 85,
    mmlu: 84,
    gpqa: 82,
    humaneval: 83,
    lmsysElo: 1410,
    description: "Version équilibrée GPT-5.6, optimale pour usage général et productivité.",
    capabilities: ["Langage", "Coding", "Vision", "Agents"],
    strengths: ["Équilibre perf/coût", "Écosystème OpenAI", "Fiabilité"],
    weaknesses: ["Moins fort que Sol"],
    bestFor: ["Usage général", "Productivité", "Analyse"],
    price: "$1.50/$7.50 per 1M tokens",
    apiAvailable: true,
    openSource: false,
    category: "High-End"
  },
  {
    id: "gemini-3-6-flash",
    slug: "gemini-3-6-flash",
    name: "Gemini 3.6 Flash",
    developer: "Google",
    params: "Non disclose",
    contextWindow: "1M",
    releaseYear: 2026,
    globalScore: 84,
    mmlu: 83,
    gpqa: 81,
    humaneval: 82,
    lmsysElo: 1395,
    description: "Optimisé pour agents multi-étapes et coding full-stack. Excellent rapport vitesse/performance.",
    capabilities: ["Orchestration", "Refactoring", "Raisonnement", "Agents"],
    strengths: ["Rapide", "Intégration Google", "1M tokens"],
    weaknesses: ["Moins fort en benchmarks purs"],
    bestFor: ["Agents Google", "Refactoring", "Apps Cloud"],
    price: "$1.50/$7.50 per 1M tokens",
    apiAvailable: true,
    openSource: false,
    category: "High-End"
  },
  {
    id: "nemotron-3-ultra",
    slug: "nemotron-3-ultra",
    name: "Nemotron 3 Ultra",
    developer: "NVIDIA",
    params: "55B (actif) / 550B (total)",
    contextWindow: "128K",
    releaseYear: 2026,
    globalScore: 83,
    mmlu: 82,
    gpqa: 80,
    humaneval: 81,
    lmsysElo: 1380,
    description: "Modèle open frontier NVIDIA, optimisé pour GPU NVIDIA. Gratuit en self-hosting.",
    capabilities: ["Raisonnement", "Coding", "Orchestration", "Open weights"],
    strengths: ["Open weights", "Gratuit", "Optimisé NVIDIA GPU"],
    weaknesses: ["Taille modeste", "Contexte 128K"],
    bestFor: ["Self-hosting", "GPU NVIDIA", "Research"],
    price: "Gratuit (self-host)",
    apiAvailable: true,
    openSource: true,
    category: "Open"
  },
  {
    id: "command-a-plus",
    slug: "command-a-plus",
    name: "Command A+",
    developer: "Conjecture AI",
    params: "Non disclose",
    contextWindow: "128K",
    releaseYear: 2026,
    globalScore: 82,
    mmlu: 81,
    gpqa: 79,
    humaneval: 80,
    lmsysElo: 1365,
    description: "Spécialisé agents autonomes avec excellent reasoning multi-tâches.",
    capabilities: ["Agent workflows", "Planning", "Execution multi-tâches", "Open source"],
    strengths: ["Spécialisé agents", "Bon reasoning", "Open weights"],
    weaknesses: ["Nouveau", "Communauté réduite"],
    bestFor: ["Agents autonomes", "Workflows complexes", "Automation"],
    price: "$2 per 1M tokens",
    apiAvailable: true,
    openSource: true,
    category: "High-End"
  },
  {
    id: "mistral-medium-3-5",
    slug: "mistral-medium-3-5",
    name: "Mistral Medium 3.5",
    developer: "Mistral AI",
    params: "Non disclose",
    contextWindow: "128K",
    releaseYear: 2026,
    globalScore: 81,
    mmlu: 80,
    gpqa: 78,
    humaneval: 79,
    lmsysElo: 1350,
    description: "Modèle européen performant, excellent multilingue. Options open weights.",
    capabilities: ["Multilingue EU", "Coding", "Raisonnement", "Agents"],
    strengths: ["Multilingue", "Open weights option", "Bonne doc"],
    weaknesses: ["Moins fort que leaders US"],
    bestFor: ["Europe", "Multilingue", "Coding"],
    price: "$1.50/$7.50 per 1M tokens",
    apiAvailable: true,
    openSource: true,
    category: "High-End"
  },
  {
    id: "minimax-m3",
    slug: "minimax-m3",
    name: "MiniMax-M3",
    developer: "MiniMax",
    params: "Non disclose",
    contextWindow: "1M",
    releaseYear: 2026,
    globalScore: 80,
    mmlu: 79,
    gpqa: 77,
    humaneval: 78,
    lmsysElo: 1335,
    description: "Modèle chinois avec large contexte 1M et bonnes capacités multimodales.",
    capabilities: ["Langage", "Vision", "Long contexte", "Multilingue"],
    strengths: ["1M tokens", "Bon prix", "Spécialisé Asia"],
    weaknesses: ["Moins disponible globalement"],
    bestFor: ["Applications Asie", "Long documents", "Multilingue"],
    price: "$0.80/$4 per 1M tokens",
    apiAvailable: true,
    openSource: false,
    category: "High-End"
  },
  {
    id: "gemini-3-5-flash-lite",
    slug: "gemini-3-5-flash-lite",
    name: "Gemini 3.5 Flash-Lite",
    developer: "Google",
    params: "Non disclose",
    contextWindow: "1M",
    releaseYear: 2026,
    globalScore: 79,
    mmlu: 78,
    gpqa: 76,
    humaneval: 77,
    lmsysElo: 1320,
    description: "Version allégée ultra-rapide pour high volume et faible latence.",
    capabilities: ["Rapidité", "Coding basique", "Agents légers"],
    strengths: ["Très rapide", "1M tokens", "Bon marché"],
    weaknesses: ["Performance réduite"],
    bestFor: ["High volume", "Latence faible", "Batch processing"],
    price: "$0.75/$3.75 per 1M tokens",
    apiAvailable: true,
    openSource: false,
    category: "Efficiency"
  },
  {
    id: "nemotron-3-super",
    slug: "nemotron-3-super",
    name: "Nemotron 3 Super",
    developer: "NVIDIA",
    params: "Non disclose",
    contextWindow: "128K",
    releaseYear: 2026,
    globalScore: 78,
    mmlu: 77,
    gpqa: 75,
    humaneval: 76,
    lmsysElo: 1305,
    description: "Version intermédiaire NVIDIA, bon équilibre performance/coût.",
    capabilities: ["Raisonnement", "Coding", "Vision"],
    strengths: ["Open weights", "Bon prix", "Optimisé GPU"],
    weaknesses: ["Moins fort qu'Ultra"],
    bestFor: ["Self-hosting milieu", "Balance perf/prix"],
    price: "Gratuit (self-host)",
    apiAvailable: true,
    openSource: true,
    category: "Open"
  },
  {
    id: "deepseek-v4-pro",
    slug: "deepseek-v4-pro",
    name: "DeepSeek V4 Pro",
    developer: "DeepSeek",
    params: "1.6T (49B activated)",
    contextWindow: "1M",
    releaseYear: 2026,
    globalScore: 76,
    mmlu: 74,
    gpqa: 72,
    humaneval: 75,
    lmsysElo: 1280,
    description: "Modèle MoE à prix très bas. Meilleur rapport qualité/prix du marché.",
    capabilities: ["Coding", "Knowledge", "Raisonnement"],
    strengths: ["Prix ultra-bas", "1M tokens", "Open weights"],
    weaknesses: ["Performance moyenne"],
    bestFor: ["Applications volume", "Budget limité", "Testing"],
    price: "$0.435/$0.87 per 1M tokens",
    apiAvailable: true,
    openSource: true,
    category: "Value"
  },
  {
    id: "solar-open2-250b",
    slug: "solar-open2-250b",
    name: "Solar Open2 250B",
    developer: "Upstage",
    params: "250B",
    contextWindow: "32K",
    releaseYear: 2026,
    globalScore: 75,
    mmlu: 74,
    gpqa: 72,
    humaneval: 73,
    lmsysElo: 1265,
    description: "Modèle coréen open source avec bonne vision et architecture MoE.",
    capabilities: ["Langage", "Vision", "Coding"],
    strengths: ["Open source", "Bon vision", "Rapport qualité/prix"],
    weaknesses: ["Contexte 32K court"],
    bestFor: ["Usage général", "Vision", "Startups"],
    price: "$1 per 1M tokens",
    apiAvailable: true,
    openSource: true,
    category: "Value"
  },
  {
    id: "muse-glimmer",
    slug: "muse-glimmer",
    name: "Muse Glimmer",
    developer: "Muse AI",
    params: "360B",
    contextWindow: "200K",
    releaseYear: 2026,
    globalScore: 74,
    mmlu: 73,
    gpqa: 71,
    humaneval: 72,
    lmsysElo: 1250,
    description: "Version high-performance pour coding rapide et prototypage.",
    capabilities: ["Coding rapide", "Raisonnement", "Agents"],
    strengths: ["Vitesse", "Bon coding", "Prix moyen"],
    weaknesses: ["Moins testé en prod"],
    bestFor: ["Prototypage rapide", "Coding itératif"],
    price: "$2 per 1M tokens",
    apiAvailable: true,
    openSource: false,
    category: "High-End"
  },
  {
    id: "claude-4-5-haiku",
    slug: "claude-4-5-haiku",
    name: "Claude 4.5 Haiku",
    developer: "Anthropic",
    params: "Non disclose",
    contextWindow: "200K",
    releaseYear: 2026,
    globalScore: 72,
    mmlu: 71,
    gpqa: 69,
    humaneval: 70,
    lmsysElo: 1220,
    description: "Version rapide et économique Claude pour usage quotidien.",
    capabilities: ["Langage rapide", "Coding basique", "Assistant"],
    strengths: ["Rapide", "Bon marché", "Fiable"],
    weaknesses: ["Moins performant"],
    bestFor: ["Usage quotidien", "Chat", "Tâches simples"],
    price: "$0.25/$1.25 per 1M tokens",
    apiAvailable: true,
    openSource: false,
    category: "Efficiency"
  },
  {
    id: "gpt-oss-120b",
    slug: "gpt-oss-120b",
    name: "gpt-oss-120b",
    developer: "Open-source community",
    params: "120B",
    contextWindow: "32K",
    releaseYear: 2026,
    globalScore: 70,
    mmlu: 68,
    gpqa: 67,
    humaneval: 69,
    lmsysElo: 1190,
    description: "Modèle communautaire open-source basé architecture GPT-4.",
    capabilities: ["Langage", "Coding", "Open source"],
    strengths: ["Open weights", "Community", "Gratuit"],
    weaknesses: ["Contexte court", "Perf limitée"],
    bestFor: ["Self-hosting", "Éducation", "Testing"],
    price: "Gratuit",
    apiAvailable: false,
    openSource: true,
    category: "Open"
  },
  {
    id: "nemotron-3-5-lightning",
    slug: "nemotron-3-5-lightning",
    name: "Nemotron 3.5 Lightning",
    developer: "NVIDIA",
    params: "Non disclose",
    contextWindow: "64K",
    releaseYear: 2026,
    globalScore: 69,
    mmlu: 68,
    gpqa: 66,
    humaneval: 67,
    lmsysElo: 1175,
    description: "Version ultra-rapide pour latency critique et temps réel.",
    capabilities: ["Rapidité extrême", "Réponse temps réel"],
    strengths: ["Très rapide", "Faible latence", "Open"],
    weaknesses: ["Contexte court", "Perf moindre"],
    bestFor: ["Temps réel", "Chatbots", "API haute fréquence"],
    price: "Gratuit (self-host)",
    apiAvailable: true,
    openSource: true,
    category: "Efficiency"
  },
  {
    id: "motif-3",
    slug: "motif-3",
    name: "Motif 3",
    developer: "Motif AI",
    params: "Non disclose",
    contextWindow: "200K",
    releaseYear: 2026,
    globalScore: 68,
    mmlu: 67,
    gpqa: 65,
    humaneval: 66,
    lmsysElo: 1160,
    description: "Nouveau venu prometteur avec bon équilibre performance/coût.",
    capabilities: ["Langage", "Coding", "Analyse"],
    strengths: ["Prix compétitif", "Interface simple"],
    weaknesses: ["Moins testé", "Communauté réduite"],
    bestFor: ["Startups", "PMV rapide", "Prototypage"],
    price: "$1 per 1M tokens",
    apiAvailable: true,
    openSource: false,
    category: "Value"
  },
  {
    id: "inkling",
    slug: "inkling",
    name: "Inkling",
    developer: "Inkling AI",
    params: "Non disclose",
    contextWindow: "128K",
    releaseYear: 2026,
    globalScore: 66,
    mmlu: 65,
    gpqa: 63,
    humaneval: 64,
    lmsysElo: 1130,
    description: "Modèle émergent axé créativité et raisonnement.",
    capabilities: ["Création contenu", "Raisonnement", "Analyse"],
    strengths: ["Créativité", "Prix bas"],
    weaknesses: ["Nouveau", "Benchmarks limités"],
    bestFor: ["Création", "Brainstorming", "Content"],
    price: "$0.50/$2.50 per 1M tokens",
    apiAvailable: true,
    openSource: false,
    category: "Emerging"
  },
  {
    id: "ax-k2",
    slug: "ax-k2",
    name: "A.X-K2",
    developer: "A.X Labs",
    params: "Non disclose",
    contextWindow: "128K",
    releaseYear: 2026,
    globalScore: 65,
    mmlu: 64,
    gpqa: 62,
    humaneval: 63,
    lmsysElo: 1115,
    description: "Nouveau modèle avec approche innovante du raisonnement.",
    capabilities: ["Raisonnement", "Analyse", "Langage"],
    strengths: ["Approche unique", "Prix attractif"],
    weaknesses: ["Très nouveau", "Peu de benchmarks"],
    bestFor: ["Expérimentation", "Cas niche"],
    price: "$0.75/$3.75 per 1M tokens",
    apiAvailable: true,
    openSource: false,
    category: "Emerging"
  },
  {
    id: "k-exaone-2-0",
    slug: "k-exaone-2-0",
    name: "K-EXAONE 2.0",
    developer: "LG AI",
    params: "Non disclose",
    contextWindow: "32K",
    releaseYear: 2026,
    globalScore: 64,
    mmlu: 63,
    gpqa: 61,
    humaneval: 62,
    lmsysElo: 1100,
    description: "Modèle coréen LG AI, excellent pour tâches asiatiques.",
    capabilities: ["Coréen", "Multilingue", "Coding"],
    strengths: ["Coréen excellent", "Open weights", "Bon prix"],
    weaknesses: ["Contexte court", "Support ASIE"],
    bestFor: ["Applications Corée", "Traduction", "Local ASIE"],
    price: "$0.50/$2.50 per 1M tokens",
    apiAvailable: true,
    openSource: true,
    category: "Regional"
  }
];

// Get model by slug
function getModelBySlug(slug) {
  return MODELS_DATA.find(m => m.slug === slug) || null;
}

// Get all models
function getAllModels() {
  return MODELS_DATA;
}

// Get models by category
function getModelsByCategory(category) {
  return MODELS_DATA.filter(m => m.category === category);
}

// Get top models by score
function getTopModels(limit = 10) {
  return [...MODELS_DATA].sort((a, b) => b.globalScore - a.globalScore).slice(0, limit);
}

// Get top models by LMSYS Elo
function getTopModelsByElo(limit = 10) {
  return [...MODELS_DATA].filter(m => m.lmsysElo).sort((a, b) => b.lmsysElo - a.lmsysElo).slice(0, limit);
}

// Generate chart data for model
function getModelChartData(model) {
  return {
    labels: ['MMLU', 'GPQA', 'HumanEval', 'LMSYS'],
    datasets: [{
      label: model.name,
      data: [model.mmlu, model.gpqa, model.humaneval, model.lmsysElo ? model.lmsysElo - 1000 : 0],
      backgroundColor: '#3a83f7',
      borderRadius: 8
    }]
  };
}

// Get competitor models for comparison
function getCompetitorModels(model) {
  return MODELS_DATA
    .filter(m => m.id !== model.id && m.category === model.category)
    .sort((a, b) => b.globalScore - a.globalScore)
    .slice(0, 5);
}

// Export for browser
if (typeof module !== 'undefined' && module.exports) {
  module.exports = { MODELS_DATA, getModelBySlug, getAllModels, getModelsByCategory, getTopModels, getTopModelsByElo, getModelChartData, getCompetitorModels };
}